apiVersion: v1

kind: Pod

metadata:

  name: myapp
  labels: 
    app: frontend

spec:

  containers:

    - name: myapp

      image: 472108177454.dkr.ecr.us-east-1.amazonaws.com/my_app:latest

      env:

        - name: DBHOST

          value: "mongo"
        
        - name: DBPORT

          value: "3306"
          
        - name: DBUSER

          value: "root"
          
        - name: DBPWD

          value: "pw"
          
        - name: APP_COLOR

          value: "pink"
      ports:
        - containerPort: 8080  
